### ISSUE TITLE
Please add context menu integration

### ISSUE THREAD

**Issue by kotenok2000** [SamuelTulach/VirusTotalUploader#70] opened 2021-02-04 16:15 UTC
^

**Comment by vertigo220** [comment] 2021-02-09 01:13
I agree this would be a nice option, but in case you didn't know, it's there, it's just in the 'Send to' menu. If you want to add it to the main menu, you can easily do so with a small registry edit. Either manually add these or just use the .reg file (need to remove the .txt extension for it to work, then just double-click to add it):

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shell\VirusTotal Uploader]
"Icon"="\"C:\\Program Files (x86)\\VirusTotal Uploader\\uploader.exe\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\*\shell\VirusTotal Uploader\command]
@="\"C:\\Program Files (x86)\\VirusTotal Uploader\\uploader.exe\" \"%1\""

[Add VirusTotal Uploader to Context Menu.reg.txt](https://github.com/SamuelTulach/VirusTotalUploader/files/5947957/Add.VirusTotal.Uploader.to.Context.Menu.reg.txt)

**Comment by SamuelTulach** [comment] 2021-02-09 07:42
Seems to be a duplicate of #37. The program itself does not manage the context menu shortcut as it was used to do before. Now it's managed by the setup so if you uninstall it with provided uninstaller, it will also remove the context menu.

Please note that it's unter "Send to".

![screenshot](https://user-images.githubusercontent.com/16323119/81683565-89e7f580-9456-11ea-9b14-def9811d779f.png)

**Closed by SamuelTulach** 2021-02-09 07:42 UTC

**Comment by madmax2** [comment] 2023-04-25 03:14
@vertigo220
can you update the reg file to include the virus total icon?
the current icon looks like the standard exe program icon which some people now associate as being suspicious/unknown program 

https://i.imgur.com/c3kli2G.png

**Comment by vertigo220** [comment] 2023-04-25 14:20
@madmax2 It already does. That's what the icon line does. I just tested it by installing the latest version and running the .reg file and it shows the VTU icon. If it's not working for you, something isn't working right. Make sure you installed it to the default location, the one in my above comment (though if you didn't, the context menu entry wouldn't even work). Also, you may want to try restarting your computer or at least the shell (explorer.exe), though that *shouldn't* be necessary. If it's still not working, the only other thing I can think of is maybe you're on Windows 11 and something is different there. If that's the case, let me know, and I'd have to look into it, though I'm very busy right now and frankly don't really do anything dealing with W11.

**Comment by vertigo220** [comment] 2023-04-25 14:30
> How doi make мег upload automatically fromcontext menu without pressing upload button?

I'm not sure, as mine already does. I don't remember if I changed a setting, but I don't see one for it. I only have to click the button if I drag a file onto it, which I never do.

**Comment by kotenok2000** [comment] 2023-04-25 14:32
It runs with following command for me.

"e:\Program Files (x86)\VirusTotal Uploader\uploader.exe" 
"C:\Users\frolo\Desktop\Dolphin-x64\Dolphin.exe"

**Comment by madmax2** [comment] 2023-05-29 03:13
@vertigo220 can you upload reg file to remove the right context menu that your original reg file added.

**Comment by vertigo220** [comment] 2023-05-29 14:59
Just edit the file and replace everything after the equal signs with a hyphen ("-", no quotes).

**Comment by madmax2** [comment] 2023-05-29 15:20
@vertigo220  like this?

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes*\shell\VirusTotal Uploader]
"Icon"=-

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes*\shell\VirusTotal Uploader\command]
@=-


would still be good if you added a uninstall txt file or reg file to your original post
So others don't need to repeat the same thing here

**Comment by vertigo220** [comment] 2023-05-29 15:37
Yes

**Comment by madmax2** [comment] 2023-07-07 07:21
@vertigo220 just tried what you suggested and it does not remove the context menu item that your reg file added.
please upload a fix or test the example I posted that you said to confirm if it works or not.


[HKEY_LOCAL_MACHINE\SOFTWARE\Classes*\shell\VirusTotal Uploader]
"Icon"=-

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes*\shell\VirusTotal Uploader\command]
@=-

**Comment by vertigo220** [comment] 2023-07-07 23:49
Will be a bit before I can. Did you reboot?

Jul 7, 2023 1:21:21 AM Tyler Durden ***@***.***' via 33Mail ***@***.***>:

**Comment by madmax2** [comment] 2023-07-08 00:18
@vertigo220 yeah as mentioned in my comment,  i did rebooted

BTW your last comment has a lot of extra detail/words, not sure if that is sensitive data or needed.

**Comment by vertigo220** [comment] 2023-07-08 01:50
New tested file uploaded to original comment. Thanks for the heads up about the additional info. Shouldn't really matter that it was posted, but not great that GitHub does that. I certainly didn't expect that using the reply to email to post a comment here would post all that stuff. Guess I'll have to not use that feature anymore.
