### ISSUE TITLE
Error occur on checking file

### ISSUE THREAD

**Issue by maxchu92** [SamuelTulach/VirusTotalUploader#11] opened 2019-02-28 06:55 UTC
BootDevice : \Device\HarddiskVolume2
BuildNumber : 17763
BuildType : Multiprocessor Free
Caption : Microsoft Windows 10 Enterprise
CodeSet : 1252
CountryCode : 1
CreationClassName : Win32_OperatingSystem
CSCreationClassName : Win32_ComputerSystem
CSDVersion : 
CSName : UNKNOWN
CurrentTimeZone : 480
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available : True
DataExecutionPrevention_Drivers : True
DataExecutionPrevention_SupportPolicy : 2
Debug : False
Description : 
Distributed : False
EncryptionLevel : 256
ForegroundApplicationBoost : 2
FreePhysicalMemory : 8888336
FreeSpaceInPagingFiles : 2451608
FreeVirtualMemory : 8340336
InstallDate : 20190119220738.000000+480
LargeSystemCache : 
LastBootUpTime : 20190227161319.500000+480
LocalDateTime : 20190228145417.589000+480
Locale : 0409
Manufacturer : Microsoft Corporation
MaxNumberOfProcesses : 4294967295
MaxProcessMemorySize : 137438953344
MUILanguages : System.String[]
Name : Microsoft Windows 10 Enterprise|C:\Windows|\Device\Harddisk0\Partition4
NumberOfLicensedUsers : 
NumberOfProcesses : 264
NumberOfUsers : 2
OperatingSystemSKU : 4
Organization : 
OSArchitecture : 64-bit
OSLanguage : 1033
OSProductSuite : 256
OSType : 18
OtherTypeDescription : 
PAEEnabled : 
PlusProductID : 
PlusVersionNumber : 
PortableOperatingSystem : False
Primary : True
ProductType : 1
RegisteredUser : MaxChu
SerialNumber : 00329-10438-22155-AA678
ServicePackMajorVersion : 0
ServicePackMinorVersion : 0
SizeStoredInPagingFiles : 2490368
Status : OK
SuiteMask : 272
SystemDevice : \Device\HarddiskVolume4
SystemDirectory : C:\Windows\system32
SystemDrive : C:
TotalSwapSpaceSize : 
TotalVirtualMemorySize : 19160380
TotalVisibleMemorySize : 16670012
Version : 10.0.17763
WindowsDirectory : C:\Windows

BootDevice : \Device\HarddiskVolume2
BuildNumber : 17763
BuildType : Multiprocessor Free
Caption : Microsoft Windows 10 Enterprise
CodeSet : 1252
CountryCode : 1
CreationClassName : Win32_OperatingSystem
CSCreationClassName : Win32_ComputerSystem
CSDVersion : 
CSName : UNKNOWN
CurrentTimeZone : 480
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available : True
DataExecutionPrevention_Drivers : True
DataExecutionPrevention_SupportPolicy : 2
Debug : False
Description : 
Distributed : False
EncryptionLevel : 256
ForegroundApplicationBoost : 2
FreePhysicalMemory : 8888336
FreeSpaceInPagingFiles : 2451608
FreeVirtualMemory : 8340336
InstallDate : 20190119220738.000000+480
LargeSystemCache : 
LastBootUpTime : 20190227161319.500000+480
LocalDateTime : 20190228145417.589000+480
Locale : 0409
Manufacturer : Microsoft Corporation
MaxNumberOfProcesses : 4294967295
MaxProcessMemorySize : 137438953344
MUILanguages : System.String[]
Name : Microsoft Windows 10 Enterprise|C:\Windows|\Device\Harddisk0\Partition4
NumberOfLicensedUsers : 
NumberOfProcesses : 264
NumberOfUsers : 2
OperatingSystemSKU : 4
Organization : 
OSArchitecture : 64-bit
OSLanguage : 1033
OSProductSuite : 256
OSType : 18
OtherTypeDescription : 
PAEEnabled : 
PlusProductID : 
PlusVersionNumber : 
PortableOperatingSystem : False
Primary : True
ProductType : 1
RegisteredUser : MaxChu
SerialNumber : 00329-10438-22155-AA678
ServicePackMajorVersion : 0
ServicePackMinorVersion : 0
SizeStoredInPagingFiles : 2490368
Status : OK
SuiteMask : 272
SystemDevice : \Device\HarddiskVolume4
SystemDirectory : C:\Windows\system32
SystemDrive : C:
TotalSwapSpaceSize : 
TotalVirtualMemorySize : 19160380
TotalVisibleMemorySize : 16670012
Version : 10.0.17763
WindowsDirectory : C:\Windows

There is no valid response from VirusTotal. Please check if your internet connection, API key and firewall.

Response error message: The request was aborted.
Response exception: System.Net.WebException: The request was aborted.
Response: 

OE: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at VirusTotal_Uploader.Main.<UploadFile>b__12_1(IRestResponse response) in D:\ZProjects\VirusTotalUploader-master\VirusTotal Uploader\Main.cs:line 162

**Comment by SamuelTulach** [comment] 2019-03-03 16:41
Can you please check if it is not duplicate of #5 ?

**Comment by SamuelTulach** [comment] 2019-03-12 16:05
I quess it is a duplicate. If you think it is not a duplicate, please send some more info (for example if it is happening only if oyu use content menu or something like that)

**Closed as completed by SamuelTulach** 2019-03-12 16:05 UTC
